(function () {
    'use strict';

    define([
            'model/accessListOperation',
            'model/accessRequest',
            'model/codeMapping',
            'model/codeSet',
            'model/company',
            'model/companyContainer',
            'model/organization',
            'model/person',
            'model/principalAccessList',
            'model/template',
            'model/translation',
            'model/userGroup',
            'model/userPrincipal',
            'model/user',
            'model/timeZone',
            'model/vacancy',
            'model/salarySought',
            'model/candidateProfile',
            'model/candidateProfileContainer',
            'model/vacancySearchResult',
            'model/vacancySearchParameter',
            'model/vacancyApplicant',
            'model/vacancyApplication',
            'model/candidateProfileSearchParameter',
            'model/companyCandidateProfileSearchParameter',
            'model/companyDiscipline',
            'model/companyRequirement',
            'model/content',
            'model/quarterlyMagazine',
            'model/quarterlyMagazineContainer',
            'model/companyRedundantProfile',
            'model/companySponsorshipPackage',
            'model/companyGraduateRecruitment',
            'model/companyEquipment',
            'model/companyEquipmentContainer',
            'model/documentlibrary',
            //'model/mentoringPortal',
            'model/documentLibraryContainer',
            'model/vacancyApplicantMailParameters',
            'model/PagedCandidateProfileContainer',
            'model/pagedVacancyApplication',
            'model/adminQuaterlyAwardsNominationForm',
            'model/pagedVacancy',
            'model/companyInnovativePortal',
            'model/companyInnovativePortalContainer',
            'model/companyTechnologyShowcasePortal',
            'model/companyTechnologyPortalContainer'],
        function (AccessListOperation,
                  AccessRequest,
                  CodeMapping,
                  CodeSet,
                  Company,
                  CompanyContainer,
                  Organization,
                  Person,
                  PrincipalAccessList,
                  Template,
                  Translation,
                  UserGroup,
                  UserPrincipal,
                  User,
                  TimeZone,
                  Vacancy,
                  SalarySought,
                  CandidateProfile,
                  CandidateProfileContainer,
                  VacancySearchResult,
                  VacancySearchParameter,
                  VacancyApplicant,
                  VacancyApplication,
                  CandidateProfileSearchParameter,
                  CompanyCandidateProfileSearchParameter,
                  CompanyDiscipline,
                  CompanyRequirement,
                  Content,
                  QuarterlyMagazine,
                  QuarterlyMagazineContainer,
                  CompanyRedundantProfile,
                  CompanySponsorshipPackage,
                  CompanyGraduateRecruitment,
                  CompanyEquipment,
                  CompanyEquipmentContainer,
                  DocumentLibrary,
                  //MentoringPortal,
                  DocumentLibraryContainer,
                  VacancyApplicantMailParameters,
                  PagedCandidateProfileContainer,
                  PagedVacancyApplication,
                  AdminQuaterlyAwardsNominationForm,
                  PagedVacancy,
                  companyInnovativePortal,
                  CompanyInnovativePortalContainer,
                  companyTechnologyPortal,
                  CompanyTechnologyPortalContainer
            ) {

            var model = {
                AccessListOperation: AccessListOperation,
                AccessRequest: AccessRequest,
                CodeMapping: CodeMapping,
                CodeSet: CodeSet,
                Event: Event,
                Company: Company,
                CompanyContainer: CompanyContainer,
                Organization: Organization,
                Person: Person,
                PrincipalAccessList: PrincipalAccessList,
                Template: Template,
                Translation: Translation,
                UserGroup: UserGroup,
                UserPrincipal: UserPrincipal,
                User: User,
                timeZone: TimeZone,
                Vacancy: Vacancy,
                SalarySought: SalarySought,
                CandidateProfile: CandidateProfile,
                CandidateProfileContainer: CandidateProfileContainer,
                VacancySearchResult: VacancySearchResult,
                VacancySearchParameter: VacancySearchParameter,
                VacancyApplicant: VacancyApplicant,
                VacancyApplication: VacancyApplication,
                CandidateProfileSearchParameter: CandidateProfileSearchParameter,
                CompanyCandidateProfileSearchParameter: CompanyCandidateProfileSearchParameter,
                CompanyDiscipline: CompanyDiscipline,
                CompanyRequirement: CompanyRequirement,
                Content: Content,
                QuarterlyMagazine: QuarterlyMagazine,
                QuarterlyMagazineContainer: QuarterlyMagazineContainer,
                CompanyRedundantProfile: CompanyRedundantProfile,
                CompanySponsorshipPackage: CompanySponsorshipPackage,
                CompanyGraduateRecruitment: CompanyGraduateRecruitment,
                CompanyEquipment: CompanyEquipment,
                CompanyEquipmentContainer: CompanyEquipmentContainer,
                DocumentLibrary: DocumentLibrary,
                //MentoringPortal: MentoringPortal,
                DocumentLibraryContainer: DocumentLibraryContainer,
                VacancyApplicantMailParameters: VacancyApplicantMailParameters,
                PagedCandidateProfileContainer: PagedCandidateProfileContainer,
                PagedVacancyApplication: PagedVacancyApplication,
                AdminQuaterlyAwardsNominationForm: AdminQuaterlyAwardsNominationForm,
                PagedVacancy: PagedVacancy,
                companyInnovativePortal: companyInnovativePortal,
                CompanyInnovativePortalContainer: CompanyInnovativePortalContainer,
                companyTechnologyPortal: companyTechnologyPortal,
                CompanyTechnologyPortalContainer: CompanyTechnologyPortalContainer
            };

            return model;
        });
})();
